package io.github.octaviusframework.db.core.type

import io.github.octaviusframework.db.api.exception.TypeMappingException
import io.github.octaviusframework.db.api.exception.TypeMappingExceptionMessage
import io.github.octaviusframework.db.core.type.registry.PgEnumDefinition
import kotlinx.serialization.KSerializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * A specialized JSON serializer for Enums that are mapped to PostgreSQL types.
 *
 * It uses the mapping definitions generated by TypeRegistry to serialize Kotlin
 * enum values to their exact string representation expected by PostgreSQL, and
 * deserialize them back.
 */
internal class PgEnumSerializer(private val definition: PgEnumDefinition) : KSerializer<Enum<*>> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor(
        serialName = definition.kClass.qualifiedName ?: definition.typeName.toString(),
        kind = PrimitiveKind.STRING
    )

    override fun serialize(encoder: Encoder, value: Enum<*>) {
        val mappedValue = definition.enumToValueMap[value] ?: throw TypeMappingException(
            messageEnum = TypeMappingExceptionMessage.ENUM_CONVERSION_FAILED,
            value = value,
            targetType = definition.typeName.toString()
        )
        encoder.encodeString(mappedValue)
    }

    override fun deserialize(decoder: Decoder): Enum<*> {
        val stringValue = decoder.decodeString()
        return definition.valueToEnumMap[stringValue]
            ?: throw TypeMappingException(
                messageEnum = TypeMappingExceptionMessage.ENUM_CONVERSION_FAILED,
                value = stringValue,
                targetType = definition.typeName.toString()
            )
    }
}
